title: Ashley Goldstein # your name (or website title) here
logo: "/images/profile.jpeg" # your photo (or logo) here
description: > # your text below
  Currently pursuing a M.Sc in Business Analytics at the University of Utah with a background in forensic chemistry and intraoperative monitoring
  <br><br>
  Open to any opportunity to analyze healthcare and biotech data.
  <br><br>
  <a href="https://www.linkedin.com/in/ashley-goldstein-2b12661b8">View My LinkedIn Profile</a>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
